name: mlops-api
channels:
    - conda-forge
    -defaults
dependecies:
    - numpy
    - pandas
    - scikit-learn
    - pytest
    - requests
    - fastapi==0.63.0
    - uvicorn
    - gunicorn
    - dvc
    - jupyter
    - jupyterlab